  version:  "3"
  tasks:
    build:
      desc: Build the app
      cmds:
        - GOFLAGS=-mod=mod go build -o bin/goBlockChain  github.com/streamdp/goblockchain/internal
    run:
      desc: Run the app
      cmds:
        - GOFLAGS=-mod=mod go run  github.com/streamdp/goblockchain/internal